# This is a basic workflow to help you get started with Actions
name: Deploy Hugo Site

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION : us-east-1 
  BUCKET_NAME: mattstatham.dev
permissions:
      id-token: write   
      contents: read   
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Install hugo
        run: sudo apt install hugo

      - name: Install aws cli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64
          rootdir: ""
          workdir: "" 

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Build
        run: hugo --minify

      - name: Upload files to S3
        run: aws s3 sync public/ s3://${{ env.BUCKET_NAME }}/ --exact-timestamps --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION }} --paths "/*"
